messages:
  wrong-usage:
    - "&7/koth create <name>"
    - "&7/koth delete <name>"
    - "&7/koth setcapzone <name> <first/second>"
    - "&7/koth setcuboid <name> <first/second>"
    - "&7/koth start <name>"
    - "&7/koth stop <name>"
    - "&7/koth reset <name>"
    - "&7/koth capture <player> <name>"
  no-permissions: "&cYou don't have permission to execute this command."
  koth-exists: "&cKoth already exists"
  koth-not-exists: "&cKoth doesn't exists."
  koth-created: "&aSuccessfully created koth"
  koth-removed: "&aSuccessfully removed koth"
  captime-set: "&cSuccessfully set captime"
  capzone-claimed: "&aSuccessfully claimed capzone."
  cuboid-claimed: "&aSuccessfully claimed cuboid"
  koth-capping: "&cKoth is currently under control"
  koth-lost: "&cKoth control has been lost"
  koth-capped: "&cKoth has been capped"
  koth-started: "&aSuccessfully started koth"
  koth-stopped: "&aSuccesfully stopped koth"
  koth-running: "&cKoth is currently running"
  koth-not-running: "&cKoth is not running."
  koth-reset: "&aSuccessfully reset koth timer."
  koth-capture: "&aSuccessfully gave reward to captured player"
  koth-next: "&cNext koth is in %timer% seconds"
koth:
  schedule: 1000
  captime: 500
settings:
  reward: # placeholders -> %player%
    1:
      chance: 100
      command: ""
inventory:
  title: "&aInventory"
  size: 36
  item:
    item: "REDSTONE_BLOCK"
    name: "&cKoth Info"
    lore-null:
      - ""
      - "NO KOTH"
      - ''
    lore:
      - ""
      - "%koth%"
      - "%capper%"
      - "%control%"
      - "%timer%"
      - ""
    slot: 1