messages:
  wrong-usage:
    - ""
  no-permissions: "&cYou don't have permission to execute this command."
  koth-exists: "&cKoth already exists"
  koth-not-exists: "&cKoth doesn't exists."
  koth-created: "&aSuccessfully created koth"
  koth-removed: "&aSuccessfully removed koth"
  captime-set: "&cSuccessfully set captime"
  capzone-claimed: "&aSuccessfully claimed capzone."
  cuboid-claimed: "&aSuccessfully claimed cuboid"
  koth-capping: "&cKoth is currently under control"
  koth-lost: "&cKoth control has been lost"
  koth-capped: "&cKoth has been capped"
  koth-started: "&aSuccessfully started koth"
  koth-stopped: "&aSuccesfully stopped koth"
  koth-not-running: "&cKoth is not running."
koth:
  scheudle: 1000
  captime: 500
settings:
  reward: # placeholders -> %player%
    1:
      chance: 100
      command: ""